module.exports = [
  {
    群组名: "oa",
    项目名称: "h5-oa",
    gogs仓库地址: "http://",
    gitlab仓库地址: "",
    开发网址: "",
    开发Jenkins: "",
    测试网址: "",
    测试Jenkins: "",
    开发服务器路径: "root@192.168.8.123:/oa/",
    测试服务器路径: "",
    runner: "web_node11",
    机器人地址: "",
    开发环境自定义命令: "npm run build:dev",
    测试环境自定义命令: "",
  },
  {
    群组名: "ydrh",
    项目名称: "h5-gdydrh",
    gogs仓库地址: "",
    gitlab仓库地址: "",
    开发网址: "",
    开发Jenkins: "",
    测试网址: "",
    测试Jenkins: "",
    开发服务器路径: "root@192.168.8.123:/oa/",
    测试服务器路径: "",
    runner: "",
    机器人地址: "",
    开发环境自定义命令: "npm run build",
    测试环境自定义命令: "",
  },
];
