const common1 = [
    {
        "id": 90,
        "name": "xxx",
        "description": "",
        "visibility": "private",
        "full_name": "xxx / frontend / xxx",
        "created_at": "2022-04-20T10:43:47.209+08:00",
        "updated_at": "2022-04-20T10:43:47.209+08:00",
        "avatar_url": null,
        "type": "group",
        "can_edit": true,
        "edit_path": "/groups/xxx/frontend/xxx/-/edit",
        "relative_path": "/xxx/frontend/xxx",
        "permission": "Owner",
        "children_count": 5,
        "parent_id": 32,
        "subgroup_count": 0,
        "project_count": 5,
        "leave_path": "/groups/xxx/frontend/xxx/-/group_members/leave",
        "can_leave": true,
        "number_users_with_delimiter": "1",
        "markdown_description": "",
        children: [
          {
              "id": 160,
              "name": "xxx-admin",
              "description": "xxx管理平台",
              "visibility": "private",
              "full_name": "xxx / frontend / xxx / xxx-admin",
              "created_at": "2022-04-21T16:08:36.691+08:00",
              "updated_at": "2022-04-21T16:22:36.837+08:00",
              "avatar_url": null,
              "type": "project",
              "can_edit": true,
              "edit_path": "/xxx/frontend/xxx/xxx-admin/edit",
              "relative_path": "/xxx/frontend/xxx/xxx-admin",
              "permission": null,
              "star_count": 0,
              "archived": false,
              "markdown_description": ""
          },
          {
              "id": 139,
              "name": "xxx-management",
              "description": "xxx-PC\r\n支持CI/CD",
              "visibility": "private",
              "full_name": "xxx / frontend / xxx / xxx-management",
              "created_at": "2022-04-21T14:49:49.581+08:00",
              "updated_at": "2022-04-21T14:53:16.514+08:00",
              "avatar_url": null,
              "type": "project",
              "can_edit": true,
              "edit_path": "/xxx/frontend/xxx/xxx-management/edit",
              "relative_path": "/xxx/frontend/xxx/xxx-management",
              "permission": null,
              "star_count": 0,
              "archived": false,
              "markdown_description": "<p data-sourcepos=\"1:1-2:11\" dir=\"auto\">xxx-PC&#x000A;支持CI/CD</p>"
          },
      ]
    },
    {
        "id": 95,
        "name": "xxx",
        "description": "",
        "visibility": "private",
        "full_name": "xxx / frontend / xxx",
        "created_at": "2022-04-20T14:03:49.557+08:00",
        "updated_at": "2022-04-20T14:46:12.989+08:00",
        "avatar_url": null,
        "type": "group",
        "can_edit": true,
        "edit_path": "/groups/xxx/frontend/xxx/-/edit",
        "relative_path": "/xxx/frontend/xxx",
        "permission": null,
        "children_count": 45,
        "parent_id": 32,
        "subgroup_count": 0,
        "project_count": 45,
        "leave_path": "/groups/xxx/frontend/xxx/-/group_members/leave",
        "can_leave": false,
        "number_users_with_delimiter": "1",
        "markdown_description": "",
        children: [
          {
              "id": 109,
              "name": "xxx-h5",
              "description": "h5xxx",
              "visibility": "private",
              "full_name": "xxx / frontend / xxx / xxx-h5",
              "created_at": "2022-04-20T15:25:28.140+08:00",
              "updated_at": "2022-04-20T15:25:44.346+08:00",
              "avatar_url": null,
              "type": "project",
              "can_edit": true,
              "edit_path": "/xxx/frontend/xxx/xxx-h5/edit",
              "relative_path": "/xxx/frontend/xxx/xxx-h5",
              "permission": null,
              "star_count": 0,
              "archived": false,
              "markdown_description": "<p data-sourcepos=\"1:1-1:14\" dir=\"auto\">h5xxx</p>"
          },
          {
              "id": 113,
              "name": "xxx-h5-mini-parent",
              "description": "xxx-H5-小程序-家长端",
              "visibility": "private",
              "full_name": "xxx / frontend / xxx / xxx-h5-mini-parent",
              "created_at": "2022-04-20T15:45:54.487+08:00",
              "updated_at": "2022-04-20T15:45:55.476+08:00",
              "avatar_url": null,
              "type": "project",
              "can_edit": true,
              "edit_path": "/xxx/frontend/xxx/xxx-h5-mini-parent/edit",
              "relative_path": "/xxx/frontend/xxx/xxx-h5-mini-parent",
              "permission": null,
              "star_count": 0,
              "archived": false,
              "markdown_description": "<p data-sourcepos=\"1:1-1:26\" dir=\"auto\">xxx-H5-小程序-家长端</p>"
          },
        ]
    }
]
module.exports = common1